name: social_agraria
description: "Social Agraria project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  confetti: ^0.8.0
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.1.0
  flutter_dotenv: ^6.0.0
  flutter_local_notifications: ^18.0.1
  go_router: ^16.3.0
  google_sign_in: ^6.2.1
  image: ^4.5.3
  image_picker: ^1.2.1
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.4
  supabase_flutter: ^2.10.3
  timeago: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/images/
