name: tinder_agro
description: "Social app project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.4.1
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.1.0
  flutter_dotenv: ^6.0.0
  go_router: ^16.3.0
  provider: ^6.1.5+1
  supabase_flutter: ^2.10.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
